/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;
/**
 *
 * @author Home
 */
public class Administrativo extends javax.swing.JFrame {
    private static GestionDeClientes clientes = new GestionDeClientes();
    private static Inicio volver = new Inicio();
  
    /**
     * Creates new form Administrativo
     */
    public Administrativo() {
        initComponents();
        this.setLocationRelativeTo(null);          
               
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdministrativoReemplazo = new javax.swing.JPanel();
        ClienteButton = new javax.swing.JButton();
        InventarioButton = new javax.swing.JButton();
        EstadisticasButton = new javax.swing.JButton();
        VolverButton = new javax.swing.JButton();
        CerrarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelAdministrativoReemplazo.setBackground(new java.awt.Color(255, 255, 255));
        panelAdministrativoReemplazo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClienteButton.setBackground(new java.awt.Color(77, 126, 168));
        ClienteButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        ClienteButton.setForeground(new java.awt.Color(255, 255, 255));
        ClienteButton.setText("Clientes");
        ClienteButton.setBorderPainted(false);
        ClienteButton.setContentAreaFilled(false);
        ClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteButtonActionPerformed(evt);
            }
        });
        panelAdministrativoReemplazo.add(ClienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 210, 40));

        InventarioButton.setBackground(new java.awt.Color(77, 126, 168));
        InventarioButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        InventarioButton.setForeground(new java.awt.Color(255, 255, 255));
        InventarioButton.setText("Inventario");
        InventarioButton.setBorderPainted(false);
        InventarioButton.setContentAreaFilled(false);
        InventarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioButtonActionPerformed(evt);
            }
        });
        panelAdministrativoReemplazo.add(InventarioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 210, -1));

        EstadisticasButton.setBackground(new java.awt.Color(77, 126, 168));
        EstadisticasButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        EstadisticasButton.setForeground(new java.awt.Color(255, 255, 255));
        EstadisticasButton.setText("Estadísticas");
        EstadisticasButton.setBorderPainted(false);
        EstadisticasButton.setContentAreaFilled(false);
        EstadisticasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasButtonActionPerformed(evt);
            }
        });
        panelAdministrativoReemplazo.add(EstadisticasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 210, 40));

        VolverButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/216436-48.png"))); // NOI18N
        VolverButton.setBorderPainted(false);
        VolverButton.setContentAreaFilled(false);
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });
        panelAdministrativoReemplazo.add(VolverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 65));

        CerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconfinder_Delete_1493279.png"))); // NOI18N
        CerrarButton.setBorderPainted(false);
        CerrarButton.setContentAreaFilled(false);
        CerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarButtonActionPerformed(evt);
            }
        });
        panelAdministrativoReemplazo.add(CerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 80, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/stock-1863880_1280.jpg"))); // NOI18N
        panelAdministrativoReemplazo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdministrativoReemplazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdministrativoReemplazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteButtonActionPerformed
        clientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_ClienteButtonActionPerformed

    private void InventarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioButtonActionPerformed
        Inventario inv = new Inventario();
        inv.setVisible(true);
        dispose();
    }//GEN-LAST:event_InventarioButtonActionPerformed

    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        volver.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverButtonActionPerformed

    private void CerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CerrarButtonActionPerformed

    private void EstadisticasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadisticasButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Administrativo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarButton;
    private javax.swing.JButton ClienteButton;
    private javax.swing.JButton EstadisticasButton;
    private javax.swing.JButton InventarioButton;
    private javax.swing.JButton VolverButton;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel panelAdministrativoReemplazo;
    // End of variables declaration//GEN-END:variables
}
