/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.GestionInsumos;
import Entidad.Insumo;
import java.awt.Dimension;

/**
 *
 * @author ACER
 */
public class Gestion_Insumos extends javax.swing.JFrame {

    GestionInsumos gi;
    /**
     * Creates new form Gestion_Insumos
     * @param gi
     */
    public Gestion_Insumos(GestionInsumos gi) {
        this.gi=gi;
        initComponents();
        setLocationRelativeTo(null);
        System.out.println("List size: "+gi.getInsumoList().size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal_Insumos = new javax.swing.JPanel();
        panel_titulo_Insumos = new javax.swing.JPanel();
        titulo_insumos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label_buscar = new javax.swing.JLabel();
        tx_buscar = new javax.swing.JTextField();
        boton_agregar_Insumo = new javax.swing.JButton();
        panel_scroll = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        panel_principal_Insumos.setBackground(new java.awt.Color(241, 198, 241));

        panel_titulo_Insumos.setBackground(new java.awt.Color(212, 17, 200));

        titulo_insumos.setFont(new java.awt.Font("Giddyup Std", 1, 72)); // NOI18N
        titulo_insumos.setForeground(new java.awt.Color(255, 255, 255));
        titulo_insumos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_insumos.setText("Insumos");
        titulo_insumos.setToolTipText("");

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_titulo_InsumosLayout = new javax.swing.GroupLayout(panel_titulo_Insumos);
        panel_titulo_Insumos.setLayout(panel_titulo_InsumosLayout);
        panel_titulo_InsumosLayout.setHorizontalGroup(
            panel_titulo_InsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titulo_InsumosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_insumos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panel_titulo_InsumosLayout.setVerticalGroup(
            panel_titulo_InsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titulo_InsumosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_titulo_InsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_titulo_InsumosLayout.createSequentialGroup()
                .addComponent(titulo_insumos)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        label_buscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_buscar.setText("Buscar");

        tx_buscar.setToolTipText("Ingrese el nombre del insumo que desea buscar");
        tx_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_buscarActionPerformed(evt);
            }
        });

        boton_agregar_Insumo.setBackground(new java.awt.Color(217, 17, 200));
        boton_agregar_Insumo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton_agregar_Insumo.setForeground(new java.awt.Color(217, 17, 200));
        boton_agregar_Insumo.setText("+");
        boton_agregar_Insumo.setToolTipText("Añada un nuevo insumo");
        boton_agregar_Insumo.setPreferredSize(new java.awt.Dimension(80, 80));
        boton_agregar_Insumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregar_InsumoActionPerformed(evt);
            }
        });

        panel_scroll.setBackground(new java.awt.Color(217, 17, 200));
        panel_scroll.setForeground(new java.awt.Color(217, 17, 200));
        panel_scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panel_scroll.setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(180, 19, 180));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        for(int i=0; i< gi.getInsumoList().size();i++ ){
            InfoInsumo subPanel = new InfoInsumo(gi.getInsumoList().get(i));
            subPanel.setBounds(10, 10+100*i,368,90);
            subPanel.setOpaque(false);
            jPanel1.add(subPanel);
        }

        panel_scroll.setViewportView(jPanel1);

        javax.swing.GroupLayout panel_principal_InsumosLayout = new javax.swing.GroupLayout(panel_principal_Insumos);
        panel_principal_Insumos.setLayout(panel_principal_InsumosLayout);
        panel_principal_InsumosLayout.setHorizontalGroup(
            panel_principal_InsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_titulo_Insumos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principal_InsumosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_principal_InsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_scroll)
                    .addGroup(panel_principal_InsumosLayout.createSequentialGroup()
                        .addComponent(label_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tx_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(boton_agregar_Insumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panel_principal_InsumosLayout.setVerticalGroup(
            panel_principal_InsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principal_InsumosLayout.createSequentialGroup()
                .addComponent(panel_titulo_Insumos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, Short.MAX_VALUE)
                .addGroup(panel_principal_InsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principal_InsumosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(boton_agregar_Insumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_principal_InsumosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panel_principal_InsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_buscar)
                            .addComponent(tx_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(panel_scroll)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal_Insumos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal_Insumos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_buscarActionPerformed

    private void boton_agregar_InsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregar_InsumoActionPerformed
        Agregar_insumo ag=new Agregar_insumo(gi);
        ag.setVisible(true);
        
        
        System.out.println(jPanel1.getWidth()+","+ jPanel1.getHeight());
          
           if(jPanel1.getComponentCount()>3)jPanel1.setPreferredSize(new java.awt.Dimension(jPanel1.getWidth(), jPanel1.getHeight()+100));
           panel_scroll.setViewportView(jPanel1);
           count++;
           
    }//GEN-LAST:event_boton_agregar_InsumoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.removeAll();
        panel_scroll.setViewportView(jPanel1);
    }//GEN-LAST:event_jButton1ActionPerformed

    static int count=0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Insumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Insumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Insumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Insumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Insumos(new GestionInsumos()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_agregar_Insumo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_buscar;
    private javax.swing.JPanel panel_principal_Insumos;
    public static javax.swing.JScrollPane panel_scroll;
    private javax.swing.JPanel panel_titulo_Insumos;
    private javax.swing.JLabel titulo_insumos;
    private javax.swing.JTextField tx_buscar;
    // End of variables declaration//GEN-END:variables
}
