/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.Insumo;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ACER
 */
public class RecordatorioSubPanelInsumo extends javax.swing.JPanel {

    private Insumo insumo;
    /**
     * Creates new form RecordatorioSubPanelInsumo
     * 
     * 
     * dateFormat.format(fechaHoy.getTime())
     */
    public RecordatorioSubPanelInsumo(Insumo ins) {
        insumo=ins;

        
        
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Dimension arcs = new Dimension(22,22); //Border corners arcs {width,height}, change this to whatever you want
        int width = getWidth();
        int height = getHeight();
        Graphics2D graphics = (Graphics2D) g;
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);


        //Draws the rounded panel with borders.
        graphics.setColor(getBackground());
        graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint background
        graphics.setColor(getForeground());
        graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint border
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setForeground(new java.awt.Color(153, 153, 153));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(920, 80));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Date date;
        try{
            date = new SimpleDateFormat("dd/MM/yyyy").parse(insumo.getRecordatorio());
            SimpleDateFormat formato=new SimpleDateFormat("EEEE, MMM d");
            jLabel1.setText("COMPRAR INSUMO:"+insumo.getNombre()+", "+insumo.getCantidad()+" "+insumo.getUnidad()+", "+
                formato.format(date)
            );
        }catch(ParseException e){
            e.printStackTrace();
        }
        add(jLabel1);
        jLabel1.setBounds(10, 10, 890, 60);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
