/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Entidad.Cliente;
import Entidad.Pedido;
import Entidad.Postre;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.SimpleDateFormat;

/**
 *
 * @author ACER
 */
public class RecordatorioSubPanelPedido extends javax.swing.JPanel {

    private Pedido ped;
    /**
     * Creates new form RecordatorioSubPanelPedido
     */
    public RecordatorioSubPanelPedido(Pedido p) {
        ped=p;
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Dimension arcs = new Dimension(22,22); //Border corners arcs {width,height}, change this to whatever you want
        int width = getWidth();
        int height = getHeight();
        Graphics2D graphics = (Graphics2D) g;
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);


        //Draws the rounded panel with borders.
        graphics.setColor(getBackground());
        graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint background
        graphics.setColor(getForeground());
        graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint border
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        button_resolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(458, 80));
        setPreferredSize(new java.awt.Dimension(920, 100));
        setLayout(null);

        Cliente c=RecordatoriosPrincipal.CC.findCliente(ped.getIdCliente().intValue());
        Postre tipoTorta=RecordatoriosPrincipal.GP.findPostre(ped.getIdPostre().intValue());
        label1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label1.setText(c.getNombre()+", "+ped.getPorciones()+
            " personas, "+ tipoTorta.getTipo()+" "+tipoTorta.getFlavor()+". Detalles: "+ped.getDecoracion()
        );
        add(label1);
        label1.setBounds(30, 20, 770, 30);

        label2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        SimpleDateFormat formato=new SimpleDateFormat("EEEE dd");
        label2.setText(formato.format(ped.getFechaE())+" "+ped.getHoraEntrega()+"   Saldo:$"+(ped.getPrecio()-ped.getAbono()));
        add(label2);
        label2.setBounds(30, 50, 500, 30);

        button_resolver.setText("Despachar");
        button_resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_resolverActionPerformed(evt);
            }
        });
        add(button_resolver);
        button_resolver.setBounds(810, 20, 100, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void button_resolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_resolverActionPerformed
        if(!ped.getEstado()){
            ped.setEstado(Boolean.TRUE);
            RecordatoriosPrincipal.CP.upDateList(ped);
            button_resolver.setEnabled(false);
        }
    }//GEN-LAST:event_button_resolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_resolver;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
