/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author ACER
 */
public class RecordatoriosPrincipal extends javax.swing.JFrame {
    
    
    

    /**
     * Creates new form RecordatoriosPrincipal
     */
    public RecordatoriosPrincipal() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        DateFormat dateFormat = new SimpleDateFormat("EEEE, MMM d");
        Calendar fechaHoy = Calendar.getInstance();
        label_fecha_hoy.setText("Hoy: "+dateFormat.format(fechaHoy.getTime()));
        System.out.println(dateFormat.format(fechaHoy.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void addSubpanelsHoy(){
        subpanel_hoy.removeAll();
        int altura=80;
        int count=0;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        label_fecha_hoy = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subpanel_hoy = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setLayout(null);

        label_titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label_titulo.setText("Recordatorios");

        jPanel2.add(label_titulo);
        label_titulo.setBounds(10, 20, 390, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 520, 80);

        label_fecha_hoy.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label_fecha_hoy.setForeground(new java.awt.Color(255, 255, 255));
        label_fecha_hoy.setText("Hoy,");
        jPanel1.add(label_fecha_hoy);
        label_fecha_hoy.setBounds(20, 100, 480, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Esta semana:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 390, 480, 70);

        subpanel_hoy.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout subpanel_hoyLayout = new javax.swing.GroupLayout(subpanel_hoy);
        subpanel_hoy.setLayout(subpanel_hoyLayout);
        subpanel_hoyLayout.setHorizontalGroup(
            subpanel_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        subpanel_hoyLayout.setVerticalGroup(
            subpanel_hoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(subpanel_hoy);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 480, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordatoriosPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordatoriosPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordatoriosPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordatoriosPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordatoriosPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_fecha_hoy;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JPanel subpanel_hoy;
    // End of variables declaration//GEN-END:variables
}
